config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "movies#index"

  resources :movies do
    collection do
      post :search
    end
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :year, presence: true, numericality: {only_integer: true}
  validates :genre, presence: true
  validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :fetch

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def search
    respond_to do |format|
      format.turbo_stream do
        @results = @client.search(params[:title_search])
        render turbo_stream: turbo_stream.update("search_results", partial: "movies/search_results", locals: {client: @client})
      end
    end
  end

  def new
    @movie = Movie.new
    @return_path = new_movie_path
    if params[:omdb_id]
      @movie_details = @client.find_by_id(params[:omdb_id])
      @movie.url = @movie_details.poster
      @movie.title = @movie_details.title
      @movie.year = @movie_details.year
      @movie.genre = @movie_details.genre
      @movie.director = @movie_details.director
    end
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @movie = Movie.find(params[:id])
    @return_path = edit_movie_path(@movie)
    if params[:omdb_id]
      @movie_details = @client.find_by_id(params[:omdb_id])
      @movie.url = @movie_details.poster
      @movie.title = @movie_details.title
      @movie.year = @movie_details.year
      @movie.genre = @movie_details.genre
      @movie.director = @movie_details.director
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    redirect_to movies_path, status: :see_other
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :year, :genre, :director, :url)
  end

  def fetch
    @client = Omdb::Api::Client.new(api_key: "28e67bb")
  end
end

app/controllers/omdb_import_controller.rb
class OMDBImportController < ApplicationController
  def create
    movie_json = get_omdb_json(params["imdb_id"])

    movie = Movie.new(
      title: movie_json["Title"],
      release_date: movie_json["Released"],
      genre: movie_json["Genre"],
      director: movie_json["Director"],
      actors: movie_json["Actors"],
      plot: movie_json["Plot"],
      image_url: movie_json["Poster"]
    )

    respond_to do |format|
      if movie.save
        format.html { redirect_to root_path, notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  BASE_URL = "http://www.omdbapi.com/"

  def get_omdb_json(imdb_id)
    HTTParty.get("#{BASE_URL}?apikey=#{Rails.application.credentials.omdb_api_key}&i=#{imdb_id}")
  end
end

app/controllers/omdb_movies_controller.rb
class OMDBMoviesController < ApplicationController
  def index
    @result = params[:query].nil? ? nil : search_for_movies(params[:query])
  end

  private

  BASE_URL = "http://www.omdbapi.com/"

  def search_for_movies(query)
    query.nil? ? nil : HTTParty.get("#{BASE_URL}?apikey=#{Rails.application.credentials.omdb_api_key}&s=#{query}")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieDB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
		<%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<div id="form">
	<%= form_with url: search_movies_path, method: :post do |f| %>
		<%= f.search_field :title_search, oninput: "this.form.requestSubmit()", placeholder: "Search Movie title" %>
		<%= f.text_field :return_url, value: @return_path %>
	<% end %>
</div>

<div id="search_results">
</div>
<br>
<br>

<div data-controller="poster">
	<%= form_with model: movie do |form| %>
		<%= image_tag("", id: "movie_poster", data: { 'poster-target' => "image" }) %>
		<%= form.text_field :url, data: { 'poster-target' => "url" } %>
		<br><br>
		<%= form.label :title %><br>
		<%= form.text_field :title %><br><br>
		<% movie.errors.full_messages_for(:title).each do |message| %>
			<div class="alert alert-danger"><%= message %></div>
		<% end %>
		<%= form.label :year %><br>
		<%= form.text_field :year %><br><br>
		<% @movie.errors.full_messages_for(:year).each do |message| %>
			<div class="alert alert-danger"><%= message %></div>
		<% end %>
		<%= form.label :genre %><br>
		<%= form.text_field :genre %><br><br>
		<% movie.errors.full_messages_for(:genre).each do |message| %>
			<div class="alert alert-danger"><%= message %></div>
		<% end %>
		<%= form.label :director %><br>
		<%= form.text_field :director %><br><br>
		<% movie.errors.full_messages_for(:director).each do |message| %>
			<div class="alert alert-danger"><%= message %></div>
		<% end %>
	<div>
		<%= form.submit :class => 'btn btn-primary' %>
	</div>
	<% end %>
</ div>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>" class="card">
  <div class="card-body">
    <p>
      <img  width="200" height="200" src="<%= movie.image_url %>"/>
    </p>

    <p>
      <strong>Release date:</strong>
      <%= movie.release_date %>
    </p>

    <p>
      <strong>Genre:</strong>
      <%= movie.genre %>
    </p>

    <p>
      <strong>Director:</strong>
      <%= movie.director %>
    </p>

    <p>
      <strong>Actors:</strong>
      <%= movie.actors %>
    </p>

    <p>
      <strong>Plot:</strong>
      <%= movie.plot %>
    </p>

  </div>

</div>

app/views/movies/_search_results.html.erb
<% if @results.is_a? Omdb::Api::Collection %>
  <div id="showResults">
    <table>
      <% @results.each do |movie| %>
      <tr>
        <td>
            <%= link_to movie.title, "#{params[:return_url]}?omdb_id=#{movie.imdb_id}" %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
<% else %>
<% end %>

app/views/movies/edit.html.erb
<h1>Edit movie</h1>
<br>
<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
<!doctype html>
<h1>Movies</h1>
<table class="table table-bordered">
	<tbody>
    <% if @movies.count.zero? %>
      <tr>
        <td>
          No movies added yet
        </td>
      </tr>
      <% else %>
		<% @movies.each do |movie| %>

			<tr>
				<td><%= image_tag(movie.url, :height => "64")%></td>
				<td><%= link_to movie.title, movie, :class => "movieLink" %> - <%= link_to "Edit", edit_movie_path(movie), :class => "link" %> - <%= link_to "Delete", movie_path(movie), :class => "link", data: { turbo_method: :delete ,turbo_confirm: "Are you sure?" } %></td>
			</tr>
		<% end %>
  <% end %>
	</tbody>
</table>
<br>
<%= link_to "New Movie", new_movie_path, :class => "btn btn-primary" %>

app/views/movies/new.html.erb
<h1>Add new movie</h1>
<br>
<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<div data-controller="poster">
  <%= image_tag("", data: { 'poster-target' => "image" }) %>
  <%= text_field_tag :movie_url, @movie.url, data: { 'poster-target' => "url" } %>
</div>
<br>

<h1><%= @movie.title %></h1><br>

<p><b>Year</b> <%= @movie.year %></p>
<p><b>Genre</b> <%= @movie.genre %></p>
<p><b>Director</b> <%= @movie.director %></p>
<br>
<%= link_to "Delete", movie_path(@movie), :class => "btn btn-danger", data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
<%= link_to "Edit", edit_movie_path(@movie), :class => "btn btn-primary"%>

app/views/omdb_movies/_results.html.erb
<% if !@result.nil? %>

  <% if @result["Response"] == "False" %>
    <% controller.redirect_to omdb_movies_path, alert: "No results found for #{params[:query]}."%>
  <% else %>
    <% @result['Search'].each do |r| %>

      <div class="card-header">
        <img width="200" height="200" src="<%= r["Poster"] != "N/A" ? r["Poster"] : "#" %>"/>
        <h5><%= r["Title"] %></h5>

        <%= button_to("Add",
          {action: "create", controller: "omdb_import", imdb_id: r["imdbID"]},
          {method: "post", class: "btn btn-primary theme-color"})
        %>
      </div>

      <br>    

    <% end %>
  <% end %>
<% end %>

app/views/omdb_movies/index.html.erb
<p style="color: red"><%= alert %></p>

<h1>Search for a movie to add</h1>
<%= form_with(url: "/omdb_movies", method: "get") do %>
  <%= label_tag(:query, "Search for:") %>
  <%= text_field_tag(:query, "", class: "form-control", :required => 'required') %>
  <%= submit_tag("Search", :class=>"btn btn-primary theme-color") %>
<% end %>

<br>
<br>

<%= render "results", movie: @movie %>